About us
johanssonfridamaria/GruppB pull request #4
Opened 2021-02-10 13:31 UTC by stefanbergsten

2021-02-10 13:42 UTC, eilertbjurek approved these changes

2021-02-10 13:56 UTC, johanssonfridamaria requested changes
Jag la till några kommentarer. Du får gärna kolla över dom. Det är mycket som gör att appen krashar. Du kanske också kan kolla på designen vi fick igen och uppdatera så det matchar :)

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/App.vue
> +
Appen crashar eftersom det inte ligger något element i app. Importen av Aboutus saknas i den här versionen av filen.

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/App.vue
> +Styling
kommentarer måste ligga som //kommentar

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/components/Aboutus.vue
> +                <span ....>
punkterna måste ligga innanför span annars krashar appen

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/components/Aboutus.vue
> +body{
stylingen av body gör ingen skillnad på utseendet på koden. Den ska i sånt fall ligga i app om vi behöver den. Men jag tror att vi inte behöver den när vi använder bootstrap i de andra komponenterna.

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/components/Aboutus.vue
> +<style>
stylingen i componenten ska vara scoped så den ligger lokalt i komponenten <style scoped >....

2021-02-10 13:56 UTC, johanssonfridamaria commented on app/src/components/Aboutus.vue
> +}
det är en måsvinge för mycket vilket för att appen kraschar

2021-02-11 08:15 UTC, eilertbjurek approved these changes

2021-02-11 10:39 UTC, eilertbjurek approved these changes

2021-02-11 10:41 UTC, eilertbjurek approved these changes

2021-02-11 10:41 UTC, eilertbjurek approved these changes

2021-02-11 13:07 UTC, closed without merging